---
- hosts: localhost
  gather_facts: false

  vars:
    module_name: "romdir"

  tasks:
    - ansible.builtin.import_role:
        name: retronas.role.romdir

    - ansible.builtin.import_role:
        name: retronas.role.system-config
