---
- hosts: localhost
  gather_facts: false

  vars:
    module_name: "extradirs"

  tasks:
    - ansible.builtin.import_role:
        name: retronas.role.extradirs

    - ansible.builtin.import_role:
        name: retronas.role.system-config
